# Generated by Django 3.0.1 on 2022-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
