# Generated by Django 3.0.1 on 2022-11-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannaShashApp', '0003_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
