# Generated by Django 3.0.1 on 2022-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannaShashApp', '0004_deliveryprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShashlikNaUgliach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Shawerma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Food',
            new_name='Assorti',
        ),
        migrations.RenameModel(
            old_name='Drink',
            new_name='MiasnoiAssorti',
        ),
    ]
