# Generated by Django 3.0.1 on 2022-12-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannaShashApp', '0005_auto_20221212_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='assorti',
            name='itemId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miasnoiassorti',
            name='itemId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shashliknaugliach',
            name='itemId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shawerma',
            name='itemId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
