# Generated by Django 3.0.1 on 2022-12-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannaShashApp', '0006_auto_20221213_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=100)),
                ('Receiver', models.CharField(max_length=100)),
            ],
        ),
    ]
