# Generated by Django 3.0.1 on 2022-12-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wannaShashApp', '0007_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPrice',
        ),
    ]
