# Generated by Django 3.0.1 on 2023-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannaShashApp', '0008_delete_deliveryprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacingMainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpacingBox2', models.IntegerField()),
                ('SpacingBox3', models.IntegerField()),
                ('SpacingBox4', models.IntegerField()),
            ],
        ),
    ]
