# Generated by Django 3.0.1 on 2023-01-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannaShashApp', '0009_spacingmainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryCost', models.IntegerField()),
            ],
        ),
    ]
